# Blog info
blog_name: ciqulover
slogan: 此去
url: https://ycwalker.com

# Set avatar (Absolute url and relative url)
avatar: /images/avatar.jpg

# Set favicon
favicon: /images/favicon.ico

# For seo
keywords: ycwalker,前端,设计,此去,前端开发,用户体验,设计,frontend,design,nodejs,JavaScript

home_nav:
  - name: 归档
    url: /archives
    target_blank: false
  - name: 分类
    url: /categories
    target_blank: false
  - name: 关于
    url: /about
    target_blank: false
  - name: GITHUB
    url: https://github.com/ciqulover
    target_blank: true

# config page nav
page_nav:
  - name: 主页
    url: /
    target_blank: false # 不在新页面打开
  - name: 归档
    url: /archives
    target_blank: false
  - name: 分类
    url: /categories
    target_blank: false
  - name: 标签
    url: /tags/
    target_blank: false
  - name: 关于
    url: /about/
    target_blank: false
#  - name: RSS
#    url: /atom.xml
#    target_blank: true # 在新页面打开


baidu_analytics: ad593ccdd2ffe5cf791b35fee21d343d

# 如果disqus账号名没设置 那么disqus_proxy也不会生效
disqus_username: ciqu

disqus_proxy:
  # 下面两项你需要更改为自己服务器的域名和端口
  server: disqus-proxy.ycwalker.com
  port: 443   #端口号需要与后端设置一致
  # 头像路径设置
  default_avatar: /avatars/default-avatar.png
  admin_avatar: /avatars/admin-avatar.jpg
  # 脚本和css路径通常不需要更改
  script_path: /static/js/main.0d0338ae.js
  css_path: /static/css/main.0603c539.css
